# Site settings
title: Stoic Reviews
email: stoicreviews@jamestomasino.com
author: "James Tomasino"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stoicreviews.com" # the base hostname & protocol for your site
twitter_username: mr_ino
github_username:  jamestomasino
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
tag_permalink_style: pretty
# Build settings
markdown: kramdown
gems:
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll-scholar
- jekyll-press
- jekyll-tagging
