# Site settings
title: Stoic Reviews
email: stoicreviews@jamestomasino.com
author: "James Tomasino"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /articles/:categories/:title
paginate: 5
paginate_path: "/articles/page:num/"
url: "http://stoicreviews.com" # the base hostname & protocol for your site
twitter_username: mr_ino
github_username:  jamestomasino
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
tag_permalink_style: pretty
scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending
  group_by: none
  group_order: ascending
  source: _bibliography
  bibliography: references.bib
  bibliography_template: bib
  replace_strings: true
  join_strings:    true
  use_raw_bibtex_entry: false
  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"

# Build settings
markdown: kramdown
picture:
  source: images
  output: generated
  markup: picture
  presets:
    default:
      ppi: [1]
      attr:
        class: image
        itemprop: image
      source_wide:
        media: "(min-width: 1280px)"
        width: 860
      source_normal:
        media: "(min-width: 980px)"
        width: 750
      source_narrow:
        media: "(min-width: 840px)"
        width: 700
      source_narrower:
        media: "(min-width: 736px)"
        width: 610
      source_mobile:
        media: "(min-width: 0)"
        width: 610
      source_default:
        width: 860
    post:
      ppi: [1]
      attr:
        class: image postimage
        itemprop: image
      source_wide:
        media: "(min-width: 1280px)"
        width: 860
      source_normal:
        media: "(min-width: 980px)"
        width: 750
      source_narrow:
        media: "(min-width: 840px)"
        width: 700
      source_narrower:
        media: "(min-width: 736px)"
        width: 610
      source_mobile:
        media: "(min-width: 0)"
        width: 610
      source_default:
        width: 860
    sidepic:
      ppi: [1]
      attr:
        class: image
        itemprop: image
      source_normal:
        media: "(min-width: 980px)"
        width: 280
      source_narrow:
        media: "(min-width: 840px)"
        width: 200
      source_narrower:
        media: "(min-width: 736px)"
        width: 150
      source_mobile:
        media: "(min-width: 0)"
        width: 100
      source_default:
        width: 280
    section:
      ppi: [1]
      attr:
        class: image sectionimage
        itemprop: image
      source_narrow:
        media: "(min-width: 840px)"
        width: 473
      source_narrower:
        media: "(min-width: 736px)"
        width: 697
      source_mobile:
        media: "(min-width: 0)"
        width: 473
      source_default:
        width: 473

gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
- jekyll/scholar
- jekyll/tagging
- jekyll-picture-tag
