source 'https://rubygems.org'
gem 'github-pages'
gem 'jemoji'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-scholar'
gem 'jekyll-press'
gem 'jekyll-tagging'
gem 'jekyll-picture-tag', '~> 0.2.3'
